# 21M.387 Fundamentals of Music Processing
## Lab4

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from ipywidgets import interact
import IPython.display as ipd

import sys
sys.path.append("../common")

from util import *

%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 6)

## Exercise 1

Rewrite the code below to use [`enumerate`](https://docs.python.org/2/library/functions.html#enumerate) instead of explicitly keeping track of and incrementing `idx`.

In [2]:
def test_1a() :
    numbers = 2 ** np.arange(8)
    for idx,n in enumerate(numbers):
        print '%d: %d' % (idx, n)
    
test_1a()

def test_1b():
    pass

test_1b()

0: 1
1: 2
2: 4
3: 8
4: 16
5: 32
6: 64
7: 128


## Exercise 2

[List comprehension](http://www.secnetix.de/olli/Python/list_comprehensions.hawk) allows you to create arrays without a `for` loop using compact synatx.   Rewrite the function below in one line using list comprehension.

In [3]:
word_list = ['a', 'list', 'of', 'some', 'words']

def filter_four1(wlist):
    out = []
    for w in wlist:
        if len(w) == 4:
            out.append(w)
    return out


print filter_four1(word_list)

def filter_four2(wlist):
    return [word for word in word_list if len(word)==4]

print filter_four2(word_list)
print filter(lambda word: len(word)==4, word_list)

['list', 'some']
['list', 'some']
['list', 'some']


## Exercise 3

`np.dot` is used for matrix multiplication, just as it is used for vector dot products. Also useful is `.T`, which provides the transpose of a matrix.

For $\mathbf{A}$ and $\mathbf{B}$ below, calculate $\mathbf{A}^T \cdot \mathbf{B}$ and $\mathbf{A} \cdot \mathbf{B}^T$

In [4]:
a = np.array(((1,2), (3,4), (5,6)))
b = np.array(((1,-1), (1,-1), (1,-1)))

print a
print b

atb = np.dot(a.T,b)
abt = np.dot(a,b.T)

print atb
print abt

[[1 2]
 [3 4]
 [5 6]]
[[ 1 -1]
 [ 1 -1]
 [ 1 -1]]
[[  9  -9]
 [ 12 -12]]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


## Exercise 4

Matrix $\mathbf{A}$ below is $6 \times 3$.  
Matrix $\mathbf{B}$ below is $2 \times 2$.  

Use [`np.tile`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html) to create a new matrix $\mathbf{T}$ that is a _tiled_ version of $\mathbf{B}$ so that the following calculation:
$$ \mathbf{C} = \mathbf{T} \cdot \mathbf{A} $$
is valid and $\mathbf{C}$ is $2 \times 3$


In [5]:
a = np.arange(18).reshape(6,3)
b = np.arange(4).reshape(2,2)
print a
print b

t = np.tile(b,(1,3))
print t
c = np.dot(t,a)
print c

assert(c.shape == (2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[0 1]
 [2 3]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]]
[[ 27  30  33]
 [117 132 147]]


## Exercise 5

For matrix $\mathbf{A}$ below, find:
- the maximum value along each column, as a vector
- the minimum value along each row, as a vector

(hint: look up `np.min` and `np.max`).

After you have the two vectors:
- Divide $\mathbf{A}$ by the max row vector (column-wise divide)
- Subtract from $\mathbf{A}$ the min column vector (row-wise subtraciton)

In [6]:
a = np.roll(np.arange(15).reshape(3,5), 2)
print a

col_max = np.max(a,0)
col_div = a.astype(float)/col_max
print col_max
print col_div

row_min = np.min(a,1)#.reshape(3,-1)
#row_sub = a - row_min
row_sub = np.subtract(a, row_min[:,np.newaxis])
print row_min
print row_sub

[[13 14  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]]
[13 14 10 11 12]
[[ 1.          1.          0.          0.09090909  0.16666667]
 [ 0.23076923  0.28571429  0.5         0.54545455  0.58333333]
 [ 0.61538462  0.64285714  1.          1.          1.        ]]
[0 3 8]
[[13 14  0  1  2]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]]


## Exercise 6

Write the function to normalize the columns of a matrix using the $L^2$ norm.

Test your function by showing that the normalized matrix columns are all length 1.


In [7]:
def normalize_matrix(mtx):
    col_norms = np.apply_along_axis(lambda x: np.dot(x,x)**0.5, 0, mtx)
    return mtx/col_norms.astype(float)

mtx = np.roll(np.arange(3*8).reshape(3,8),2)
print mtx
normed_matrix = normalize_matrix(mtx)
print normed_matrix
print np.apply_along_axis(lambda x: np.dot(x,x) , 0, normed_matrix)


[[22 23  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
[[ 0.8221786   0.81165237  0.          0.05191741  0.09667365  0.1353881
   0.16903085  0.19841895]
 [ 0.22423053  0.24702464  0.4472136   0.46725672  0.48336824  0.49642305
   0.50709255  0.51588926]
 [ 0.52320456  0.5293385   0.89442719  0.88259602  0.87006284  0.857458
   0.84515425  0.83335958]]
[ 1.  1.  1.  1.  1.  1.  1.  1.]


## Exercise 7

Write the function `pitch_to_freq(p)` which takes a midi-pitch (scalar or vector) and returns the proper frequency of that pitch (or pitches).

Test with the call below.

In [8]:
def pitch_to_freq(p):
    return 2.0**((p-69.0)/12.0) * 440.0

print pitch_to_freq(np.array((68.5, 69, 69.5)))

[ 427.47405411  440.          452.89298412]


## Exercise 8

Write the function `bins_of_pitch()` which takes a single midi-pitch (scalar only) and returns an array of the frequency bins (i.e, values of $k$) that contribute to $\pm 0.5$ semitones around that pitch.

Inputs are: 
- `p`: MIDI pitch
- `fs`: $F_s$, the sampling frequency of the signal
- `fft_len`: $N$, the length of the DFT

Test your function below.

In [32]:
import math

def freq_to_k(freq, fs, N):
    # k periods / N samples
    # fs samples / time
    # freq = per / time = k * fs / N
    return freq * N / fs

def bins_of_pitch(p, fs, fft_len):
    bounds = [pitch_to_freq(p-0.5), pitch_to_freq(p+0.5)]
    ks = map(lambda f: freq_to_k(f,fs,fft_len), bounds)
    return range(int(math.ceil(ks[0])),
                 int(math.ceil(ks[1])))

    
"""
def try_it(power):
    fft_len = 2**power
    print 'Trying', fft_len
    for p in range(36,108):
        bins = bins_of_pitch(p,22050,fft_len)
        if len(bins) < 2: 
            print 'Failed on pitch', p
            return
    print 'Success'
"""

# should return: [40, 41, 42]
print bins_of_pitch(69, 22050, 2048)

[40, 41, 42]


## Exercise 9

Given an audio signal sampled at $F_s = 22050$, we want to create a pitch-o-gram (ie, log-frequency spectorgram) that starts at the note _C2_ (pitch = 36) and ends at _C8_ (pitch=108). Furthermore, we want to ensure that every pitch-bin can draw from at least 2 frequency-bins of the STFT spectrogram. 

What is the smallest value of $N$ (the FFT length, which must be a power of 2) needed to create the STFT to achieve this requirement?

Hint - it is very useful to use the function `bins_of_pitch()` from above.

In [35]:
#@interact(power=(5,20))

#diff between C2 and C8 speaks to the number of 
# repeats of the conversion matrix
def try_it(x):
    valid_fft_lens = [len(bins_of_pitch(p, 22050, 2**x)) >= 2 
                      for p in range(26,109)]
    return all(valid_fft_lens)

print([try_it(y) for y in range(4,20)])
#15


[False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True]
